quiniela/config/routes.rb
Rails.application.routes.draw do
  scope '/home' do 
    resources :players do
      collection do
        get :sign_up
        get :login
        get :logout
        post :login
        get 'profile/:id' => 'players#show', as: :profile
      end
    end
    resources :predictions
    resources :matches do
      collection do 
        get :all
      end
    end
    resources :teams
    resources :roles
    resources :leaderboards
    get '/', to: 'players#home', as: :home
    get '/welcome', to: 'players#root', as: :root
  end 

  scope '/api' do
    resources :api_matches
    scope '/get_token' do
      get '/', to: 'application_api#get_token'
    end
    scope '/authorize_request' do
      get '/', to: 'application_api#authorize_request'
    end
  end
end

quiniela/app/models/prediction.rb
class Prediction < ApplicationRecord
    
    # validations
    validates :player_id, presence: true
    validates :match_id, presence: true
    validates :goals1, presence: true
    validates :goals2, presence: true
    
    # associations
    belongs_to :player
    belongs_to :match
    
    # callbacks
    before_create :check_not_duplicate


    # methods
    # update awarded points based on the match result
    def self.check_awarded_points(match_id)
        Prediction.where(match_id: match_id).find_each do |prediction|
        if prediction.match.goals1.nil? || prediction.match.goals2.nil?
            prediction.update(points_awarded: 0)
        else
            points_awarded = 0
            # if match result is the same as prediction
            if prediction.goals1 == prediction.match.goals1 && prediction.goals2 == prediction.match.goals2
            points_awarded = 3
            # if match team 1 or team 2 goals are the same as prediction
            elsif prediction.goals1 == prediction.match.goals1 || prediction.goals2 == prediction.match.goals2
            points_awarded = 1
            # if winner is the same as prediction + 1
            if (prediction.match.goals1 > prediction.match.goals2 && prediction.goals1 > prediction.goals2) || (prediction.match.goals1 < prediction.match.goals2 && prediction.goals1 < prediction.goals2)
                points_awarded = 2
            end
            # if match team 1 or team 2 goals difference is the same as prediction
            elsif prediction.goals1 - prediction.goals2 == prediction.match.goals1 - prediction.match.goals2
            points_awarded = 1
            # if winner is the same as prediction + 1
            if (prediction.match.goals1 > prediction.match.goals2 && prediction.goals1 > prediction.goals2) || (prediction.match.goals1 < prediction.match.goals2 && prediction.goals1 < prediction.goals2)
                points_awarded = 2
            end
            end
            prediction.update(points_awarded: points_awarded)
        end
        end
    end
  

    # check if prediction for the same match already exists
    # if it does, cancel the creation of the new prediction

    def check_not_duplicate
        Prediction.all.each do |prediction|
            if prediction.player_id == self.player_id && prediction.match_id == self.match_id
                return false
            end
        end
    end

end

quiniela/app/controllers/predictions_controller.rb
class PredictionsController < ApplicationController
  before_action :set_prediction, only: %i[ show edit update destroy ]

  # GET /predictions or /predictions.json
  def index
    @predictions = Prediction.where(player_id: params[:player_id])

    respond_to do |format|
      format.html
      format.xml { render xml: @predictions}
      format.json { render json: @predictions}
    end
  end

  # GET /predictions/1 or /predictions/1.json
  def show
  end

  # GET /predictions/new
  def new
    @prediction = Prediction.new
    @matches = Match.all
    @match = Match.find(params[:match_id]) if params[:match_id]
    session[:saved_location] = request.referer


  end

  # GET /predictions/1/edit
  def edit
    @matches = Match.all
    @prediction = Prediction.find(params[:id])
    session[:saved_location] = request.referer


  end

  # POST /predictions or /predictions.json
  # if prediciton.check_not_duplicate returns false, it will redirect to the new prediction page
  # if it returns true, it will create the prediction
  def create    

    @prediction = Prediction.new(prediction_params)
    @prediction.player_id = session[:player_id]
    @prediction.points_awarded = 0

    if @prediction.check_not_duplicate == false
      redirect_to new_prediction_path, notice: "You have already made a prediction for this match"
      return
    end

    respond_to do |format|
      if @prediction.save
        format.html { redirect_to prediction_url(@prediction), notice: "Prediction was successfully created." }
        format.json { render :show, status: :created, location: @prediction }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @prediction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /predictions/1 or /predictions/1.json
  def update
    respond_to do |format|
      if @prediction.update(prediction_params)
        format.html { redirect_to prediction_url(@prediction), notice: "Prediction was successfully updated." }
        format.json { render :show, status: :ok, location: @prediction }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @prediction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /predictions/1 or /predictions/1.json
  def destroy
    @prediction.destroy

    respond_to do |format|
      format.html { redirect_to predictions_path(player_id: @current_player.id), notice: "Prediction was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_prediction
      @prediction = Prediction.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def prediction_params
      params.require(:prediction).permit(
        :match_id,
        :goals1,
        :goals2
      )
    end
end

quiniela/app/helpers/predictions_helper.rb
module PredictionsHelper
end

quiniela/app/views/predictions/_form.html.erb
<%= form_with(model: prediction) do |form| %>
  <% if prediction.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(prediction.errors.count, "error") %> prohibited this prediction from being saved:</h2>

      <ul>
        <% prediction.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

quiniela/app/views/predictions/_prediction.html.erb
<div id="<%= dom_id prediction %>">
</div>

quiniela/app/views/predictions/edit.html.erb
<section class="section animate__animated animate__zoomIn animate__faster">
 
    <div class="container">
    <div class="box">
      <div class="control has-text-left mt-4">
        <%= link_to prediction_path, class: "button is-danger" do %>
          <span class="icon">
            <i class="fas fa-arrow-left"></i>
          </span>
          <span>Back</span>
        <% end %>
      </div>
      <h1 class="title">Edit Prediction</h1>
      <h2 class="subtitle">
        <%= truncate(Team.find_by(id: @prediction.match.team1_id).name, length: 100) %> vs
        <%= truncate(Team.find_by(id: @prediction.match.team2_id).name, length: 100) %>
      </h2>
      
      <%= form_with model: @prediction, class: "form" do |form| %>

        <div class="field">
          <%= form.label "Goals Team #1", class: "label" %>
          <div class="control">
            <%= form.number_field :goals1, class: "input", placeholder: "Goals Team 1" %>
          </div>
        </div>

        <div class="field">
          <%= form.label "Goals Team #2", class: "label" %>
          <div class="control">
            <%= form.number_field :goals2, class: "input", placeholder: "Goals Team 2" %>
          </div>
        </div>

        <div class="field">
          <div class="control">
            <%= form.submit "Submit", class: "button is-primary" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</section>

quiniela/app/views/predictions/index.html.erb
<section class="section animate__animated animate__zoomIn animate__faster">
  <div class="container">
    <div class="box">
      <% if notice %>
      <div class="notification is-primary">
        <%= notice %>
      </div>
      <% end %>
      <div class="control has-text-left mt-4">
        <%= link_to player_path(@current_player), class: "button is-danger" do %>
          <span class="icon">
            <i class="fas fa-arrow-left"></i>
          </span>
          <span>Back</span>
        <% end %>
      </div>
      <h1 class="title">My Predictions</h1> <br>
      <h2 class="subtitle">Available</h2>
      <div class="columns is-multiline is-justify-content-center">
        <% @predictions.select { |prediction| prediction.match.date_played > Time.current }.sort_by(&:id).each do |prediction| %>
          <div class="column is-4">
            <div class="card <%= prediction.match.date_played > Time.current ? 'has-background-light' : '' %>">
                <div class="card-content has-text-centered">
                  <p class="is-size-4 has-text-weight-bold">
                    <%= truncate(Team.find_by(id: prediction.match.team1_id).name, length: 11) %> 
                    vs 
                    <%= truncate(Team.find_by(id: prediction.match.team2_id).name, length: 11) %>
                  </p> <br>

                  <p class="is-size-5">
                    <%= "Points awarded: " %>
                    <span class="icon is-small ml-4 mr-2">
                      <i class="fa fa-trophy"></i>
                    </span> 
                    <%= "-" %>
                  </p> <br>

                  <p class="is-size-5">
                    Predicted score: 
                    <span class="icon is-small ml-4 mr-2">
                      <i class="fa fa-futbol"></i>
                    </span> 
                    <%= prediction.goals1 %> - <%= prediction.goals2 %> <br> <br>
                  </p>
                  
                  <p class="is-size-5">
                    Actual score: 
                    <span class="icon is-small ml-4 mr-2">
                      <i class="fa fa-futbol"></i>
                    </span> 
                    <%= prediction.match.goals1 %> - <%= prediction.match.goals2 %> <br> <br>
                  </p>
                  <p class="is-size-6">
                    <span class="icon is-small">
                      <i class="far fa-calendar-alt"></i>
                    </span>
                    Date: <%= prediction.match.date_played %>
                  </p>
                  <%= render prediction %>
                </div>
              <footer class="card-footer">
                <a href="<%= prediction_path(prediction) %>" class="card-footer-item has-background-primary">See this prediction</a>
              </footer>
            </div>
          </div>
        <% end %>
      </div>

      <h2 class="subtitle">Finished</h2>
        <div class="columns is-multiline is-justify-content-center">
          <% @predictions.select { |prediction| prediction.match.date_played <= Time.current }.sort_by(&:created_at).reverse.each do |prediction| %>
            <div class="column is-4">
              <div class="card <%= prediction.match.date_played < Time.current ? 'has-background-light' : '' %> <%= prediction.points_awarded == 0 ? 'has-background-danger-light' : prediction.points_awarded.between?(1, 2) ? 'has-background-warning-light' : prediction.points_awarded == 3 ? 'has-background-primary-light' : '' %>">
                <div class="card-content has-text-centered">
                  <p class="is-size-4 has-text-weight-bold">
                    <%= truncate(Team.find_by(id: prediction.match.team1_id).name, length: 11) %> 
                    vs 
                    <%= truncate(Team.find_by(id: prediction.match.team2_id).name, length: 11) %>
                  </p> <br>

                  <p class="is-size-5">
                    <%= "Points awarded: " %>
                    <span class="icon is-small ml-4 mr-2">
                      <i class="fa fa-trophy"></i>
                    </span> 
                    <%= prediction.points_awarded %>
                  </p> <br>

                  <p class="is-size-5">
                    Predicted score: 
                    <span class="icon is-small ml-4 mr-2">
                      <i class="fa fa-futbol"></i>
                    </span> 
                    <%= prediction.goals1 %> - <%= prediction.goals2 %> <br> <br>
                  </p>
                  
                  <p class="is-size-5">
                    Actual score: 
                    <span class="icon is-small ml-4 mr-2">
                      <i class="fa fa-futbol"></i>
                    </span> 
                    <%= prediction.match.goals1 %> - <%= prediction.match.goals2 %> <br> <br>
                  </p>
                  <p class="is-size-6">
                    <span class="icon is-small">
                      <i class="far fa-calendar-alt"></i>
                    </span>
                    Date Played: <%= prediction.match.date_played %>
                  </p>
                  <%= render prediction %>
                </div>
                <footer class="card-footer">
                  <a href="<%= prediction_path(prediction) %>" class="card-footer-item has-background-primary-light">See this prediction</a>
                </footer>
              </div>
            </div>
          <% end %>
          <br>
      </div>
      <div class="control">
        <%= link_to "New prediction", new_prediction_path, class: "button is-primary" %>
      </div>
    </div>
  </div>
</section>

quiniela/app/views/predictions/new.html.erb
<section class="section animate__animated animate__zoomIn animate__faster">   
  <div class="container">
    <% if notice %>
      <div class="notification is-danger">
        <%= notice %>
      </div>
    <% end %>
    <div class="box">
      <div class="control has-text-left mt-4">
        <%= link_to all_matches_path, class: "button is-danger" do %>
          <span class="icon">
            <i class="fas fa-arrow-left"></i>
          </span>
          <span>Back</span>
        <% end %>
      </div>
      <h1 class="title">New Prediction</h1>
      <%= form_with model: @prediction, class: "form" do |form| %>
        <div class="field">
          <%= form.label :match_id, class: "label" %>
          <div class="control">
            <div class="select">
              <% options = @matches.where("date_played >= ?", Time.current).map { |match| [truncate(Team.find_by(id: match.team1_id).name, length: 10) + " vs " + truncate(Team.find_by(id: match.team2_id).name, length: 10), match.id] } %>
              <%= form.select :match_id, options_for_select(options, selected: @match&.id), {} %>
            </div>
          </div>
        </div>

        <div class="field">
          <%= form.label "Goals Team #1", class: "label" %>
          <div class="control">
            <%= form.number_field :goals1, class: "input", placeholder: "Goals Team 1" %>
          </div>
        </div>

        <div class="field">
          <%= form.label "Goals Team #2", class: "label" %>
          <div class="control">
            <%= form.number_field :goals2, class: "input", placeholder: "Goals Team 2" %>
          </div>
        </div>

        <div class="field">
          <div class="control">
            <%= form.submit "Submit", class: "button is-primary" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</section>

quiniela/app/views/predictions/show.html.erb
<section class="section animate__animated animate__zoomIn animate__faster">
  <div class="container"> 
    <% if notice %>
      <div class="notification is-primary">
        <%= notice %>
      </div>
    <% end %>
    <div class="box">
      <div class="control has-text-left mt-4">
        <%= link_to predictions_path(player_id: @current_player.id), class: "button is-danger" do %>
          <span class="icon">
            <i class="fas fa-arrow-left"></i>
          </span>
          <span>Back</span>
        <% end %>
      </div>
      <div class="card-content has-text-centered">
        <p class="is-size-4 has-text-weight-bold">
          <%= truncate(Team.find_by(id: @prediction.match.team1_id).name, length: 100) %> 
          vs 
          <%= truncate(Team.find_by(id: @prediction.match.team2_id).name, length: 100) %>
        </p> <br>

        <p class="is-size-5">
          <%= "Points awarded: " %>
          <span class="icon is-small ml-4 mr-2">
            <i class="fa fa-trophy"></i>
          </span> 
          <%= @prediction.points_awarded %>
        </p> <br>

        <p class="is-size-5">
          Predicted score: 
          <span class="icon is-small ml-4 mr-2">
            <i class="fa fa-futbol"></i>
          </span> 
          <%= @prediction.goals1 %> - <%= @prediction.goals2 %> <br> <br>
        </p>
        
        <p class="is-size-5">
          Actual score: 
          <span class="icon is-small ml-4 mr-2">
            <i class="fa fa-futbol"></i>
          </span> 
          <%= @prediction.match.goals1 %> - <%= @prediction.match.goals2 %> <br> <br>
        </p>
        <p class="is-size-6">
          <span class="icon is-small">
            <i class="far fa-calendar-alt"></i>
          </span>
          Date: <%= @prediction.match.date_played %>
        </p>
        <%= render @prediction %>
      </div>
      <div class="buttons is-centered">
        <% if @prediction.match.date_played < Time.current %>
          <!-- Botón deshabilitado (cuando la fecha ya ha pasado) -->
          <button class="button is-info" disabled>Edit</button>
        <% else %>
          <!-- Enlace habilitado (cuando la fecha aún no ha pasado) -->
          <%= link_to "Edit", edit_prediction_path(@prediction), class: "button is-info" %>
        <% end %>
        <%= button_to "Delete", @prediction, method: :delete, class: "button is-danger" %>
      </div>
    </div>
  </div>
</section>