quiniela/config/routes.rb
Rails.application.routes.draw do
  scope '/home' do 
    resources :players do
      collection do
        get :sign_up
        get :login
        get :logout
        post :login
        get 'profile/:id' => 'players#show', as: :profile
      end
    end
    resources :predictions
    resources :matches do
      collection do 
        get :all
      end
    end
    resources :teams
    resources :roles
    resources :leaderboards
    get '/', to: 'players#home', as: :home
    get '/welcome', to: 'players#root', as: :root
  end 

  scope '/api' do
    resources :api_matches
    scope '/get_token' do
      get '/', to: 'application_api#get_token'
    end
    scope '/authorize_request' do
      get '/', to: 'application_api#authorize_request'
    end
  end
end

quiniela/app/models/match.rb
class Match < ApplicationRecord


    # validations
    validates :team1_id, presence: true
    validates :team2_id, presence: true
    validate :different_teams


    # associations
    has_many :prediction
    has_many :team

    # callbacks
    after_destroy :delete_predictions

    # methods

    def different_teams
        if self.team1_id == self.team2_id
            errors.add(:team1_id, "can't be the same as team2_id")
        end
    end

    
    # delete all predictions for a match after match was deleted
    def delete_predictions
        Prediction.where(match_id: self.id).destroy_all
    end


end

quiniela/app/controllers/matches_controller.rb
class MatchesController < ApplicationController
    before_action :set_match, only: %i[ show edit update destroy ]
    
    # method to show all matches
    def all
        @matches = Match.all
    end

    # GET /matches or /matches.json
    def index
        @matches = Match.joins(:prediction).where(predictions: { player_id: params[:player_id] })

        respond_to do |format|
            format.html
            format.xml { render xml: @matches}
            format.json { render json: @matches}
        end

    end
    
    # GET /matches/1 or /matches/1.json
    def show
        # write match details to console
        puts "Match details:"
        puts "ID: " + @match.id.to_s
        puts "Date played: " + @match.date_played.to_s
        puts "Team 1: " + @match.team1_id.to_s
        puts "Team 2: " + @match.team2_id.to_s
        puts "Goals 1: " + @match.goals1.to_s
        puts "Goals 2: " + @match.goals2.to_s
        
    end
    
    # GET /matches/new
    def new
        @match = Match.new
        session[:saved_location] = request.referer

    end
    
    # GET /matches/1/edit
    def edit
    end
    
    # POST /matches or /matches.json
    def create
        @match = Match.new(match_params)
        
        respond_to do |format|
            if @match.save
                format.html { redirect_to match_url(@match), notice: "Match was successfully created." }
                format.json { render :show, status: :created, location: @match }
            else
                format.html { redirect_to new_match_path, notice: "Error creating match: " + @match.errors.full_messages.join(", ") }
                format.json { render json: @match.errors, status: :unprocessable_entity }
            end
        end
    end
    
    # PATCH/PUT /matches/1 or /matches/1.json
    def update
        respond_to do |format|
            if @match.update(match_params)
                format.html { redirect_to match_url(@match), notice: "Match was successfully updated." }
                format.json { render :show, status: :ok, location: @match }
                Prediction.check_awarded_points(@match.id)

            else
                format.html { render :edit, status: :unprocessable_entity }
                format.json { render json: @match.errors, status: :unprocessable_entity }
            end
        end
        UpdatePointsJob.perform_later()
        flash.discard(:notice)
        flash.discard(:alert)
    end
    
    # DELETE /matches/1 or /matches/1.json
    def destroy
        @match.destroy
        respond_to do |format|
            format.html { redirect_to all_matches_path, notice: "Match was successfully destroyed." }
            format.json { head :no_content }
        end
    end
    
    private
    # Use callbacks to share common setup or constraints between actions.
    def set_match
        @match = Match.find(params[:id])
    end
    
    # Only allow a list of trusted parameters through.
    def match_params
        params.require(:match).permit(
            :id,
            :date_played,
            :team1_id,
            :team2_id,
            :goals1,
            :goals2
        )
    end
end

quiniela/app/helpers/matches_helper.rb
module MatchesHelper
end

quiniela/app/views/matches/_form.html.erb
<%= form_with(model: match) do |form| %>
  <% if match.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(match.errors.count, "error") %> prohibited this match from being saved:</h2>

      <ul>
        <% match.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

quiniela/app/views/matches/_match.html.erb
<div id="<%= dom_id match %>">
</div>

quiniela/app/views/matches/all.html.erb
<section class="section animate__animated animate__zoomIn animate__faster">
  <div class="container">
    <div class="box">
    <% if notice %>
      <div class="notification is-primary">
        <%= notice %>
      </div>
    <% end %>
      <div class="control has-text-left mt-4">
        <%= link_to player_path(@current_player), class: "button is-danger" do %>
          <span class="icon">
            <i class="fas fa-arrow-left"></i>
          </span>
          <span>Back</span>
        <% end %>
      </div>
      <h1 class="title">Matches</h1> <br>
      <h2 class="subtitle">Available Matches</h2>
      <div class="columns is-multiline is-justify-content-center">
        <% @matches.select { |match| match.date_played > Time.current }.sort_by(&:date_played).each do |match| %>
          <div class="column is-4">
            <div class="card <%= match.date_played > Time.current ? 'has-background-primary-light' : '' %>">
              <div class="card-content has-text-centered">
                <p class="is-size-4 has-text-weight-bold">
                  <%= truncate(Team.find_by(id: match.team1_id).name, length: 11) %> 
                  vs 
                  <%= truncate(Team.find_by(id: match.team2_id).name, length: 11) %>
                </p> <br>
                <p class="is-size-5">
                  <span class="icon is-small">
                    <i class="fa fa-futbol"></i>
                  </span> 
                  <%= match.goals1 %> - <%= match.goals2 %>
                </p>  <br>
                <p class="is-size-5">
                  <span class="icon is-small">
                    <i class="far fa-calendar-alt"></i>
                  </span>
                  Date: <%= match.date_played %>
                </p>
                <%= render match %>
              </div>
              <footer class="card-footer">
                <a href="<%= match_path(match) %>" class="card-footer-item has-background-primary">Show this match</a>
              </footer>
            </div>
          </div>
        <% end %>
      </div>

      <h2 class="subtitle">Past Matches</h2>
      <div class="is-flex is-overflow-x-auto">
        <div class="columns is-multiline is-justify-content-center">
          <% @matches.select { |match| match.date_played <= Time.current }.sort_by(&:date_played).reverse.each do |match| %>
            <div class="column is-4">
              <div class="card <%= match.date_played < Time.current ? 'has-background-light' : '' %>">
                <div class="card-content has-text-centered">
                  <p class="is-size-4 has-text-weight-bold">
                    <%= truncate(Team.find_by(id: match.team1_id).name, length: 11) %> 
                    vs 
                    <%= truncate(Team.find_by(id: match.team2_id).name, length: 11) %>
                  </p> <br>
                  <p class="is-size-5">
                    <span class="icon is-small">
                      <i class="fa fa-futbol"></i>
                    </span> 
                    <%= match.goals1 %> - <%= match.goals2 %>
                  </p>  <br>
                  <p class="is-size-5">
                    <span class="icon is-small">
                      <i class="far fa-calendar-alt"></i>
                    </span>
                    Date Played: <%= match.date_played %>
                  </p>
                  <%= render match %>
                </div>
                <footer class="card-footer">
                  <a href="<%= match_path(match) %>" class="card-footer-item has-background-primary-light">Show this match</a>
                </footer>
              </div>
            </div>
          <% end %>
        </div>
      </div>
      <% if @current_player.role_id == 2 %>
        <div class="control mt-5">
          <%= link_to "New match", new_match_path, class: "button is-primary" %>
        </div>
      <% end %>
    </div>
  </div>
</section>

quiniela/app/views/matches/edit.html.erb
<section class="section animate__animated animate__zoomIn animate__faster">
  <div class="container">
    <div class="box">
      <div class="control has-text-left mt-4">
        <%= link_to all_matches_path, class: "button is-danger" do %>
          <span class="icon">
            <i class="fas fa-arrow-left"></i>
          </span>
          <span>Back</span>
        <% end %>
      </div>
      <h1 class="title">Edit Match</h1>
      <h2 class="subtitle">
        <%= truncate(Team.find_by(id: @match.team1_id).name, length: 100) %> vs
        <%= truncate(Team.find_by(id: @match.team2_id).name, length: 100) %>
      </h2>

      <%= form_with model: @match, class: "form" do |form| %>
      
        <div class="field has-text-left"> <!-- Justify label to the left -->
          <%= form.label :date_played, class: "label" %>
          <div class="control">
            <%= form.date_field :date_played, class: "input" %>
          </div>
        </div>

        <div class="field has-text-left"> <!-- Justify label to the left -->
          <%= form.label :team1_id, class: "label" %>
          <div class="control">
            <div class="select">
              <%= form.collection_select :team1_id, Team.all, :id, :name, {}, class: "select" %>
            </div>
          </div>
        </div>

        <div class="field has-text-left"> <!-- Justify label to the left -->
          <%= form.label :team2_id, class: "label" %>
          <div class="control">
            <div class="select">
              <%= form.collection_select :team2_id, Team.all, :id, :name, {}, class: "select" %>
            </div>
          </div>
        </div>

        <div class="field has-text-left"> 
          <%= form.label :goals_team_1, class: "label" %>
          <div class="control">
            <div class="select">
              <% current_goals1 = @match.goals1 || "Not Played Yet" %>
              <%= form.select :goals1, options_for_select([["Not Played Yet", ""], *(0..10)], selected: current_goals1), {}, class: "input" %>
            </div>
          </div>
        </div>

        <div class="field has-text-left"> 
          <%= form.label :goals_team_2, class: "label" %>
          <div class="control">
            <div class="select">
              <% current_goals2 = @match.goals2 || "Not Played Yet" %>
              <%= form.select :goals2, options_for_select([["Not Played Yet", ""], *(0..10)], selected: current_goals2), {}, class: "input" %>
            </div>
          </div>
        </div>


        <div class="field is-grouped">
          <div class="control">
            <%= form.submit "Update Match", class: "button is-primary" %>
          </div>
        </div>
      <div>
        <%= button_to "Delete this Match", @match, method: :delete, data: { confirm: "Are you sure?" }, class: "button is-danger" %>
      </div>

      <% end %>
      <br>

    </div>
  </div>
</section>

quiniela/app/views/matches/index.html.erb
<section class="section animate__animated animate__zoomIn animate__faster">
  <div class="container">
    <div class="box">
      <% if notice %>
        <p style="color: green"><%= notice %></p>
      <% end %>
      <div class="control has-text-left mt-4">
        <%= link_to player_path(@current_player), class: "button is-danger" do %>
          <span class="icon">
            <i class="fas fa-arrow-left"></i>
          </span>
          <span>Back</span>
      <% end %>
      </div>
      <h1 class="title">My Matches</h1>

      <div class="columns is-multiline is-centered is-variable is-2">
        <% @matches.sort_by(&:id).each do |match| %>
          <div class="column is-4">
            <div class="card match-card">
              <div class="card-content has-background-light has-text-centered">
                <p class="is-size-4 has-text-weight-bold">
                  <%= truncate(Team.find_by(id: match.team1_id).name, length: 12) %> 
                  vs 
                  <%= truncate(Team.find_by(id: match.team2_id).name, length: 12) %>
                </p> <br>
                <p class="is-size-5">
                  <span class="icon is-small">
                    <i class="fa fa-futbol"></i>
                  </span> 
                  <%= match.goals1 %> - <%= match.goals2 %>
                </p>  <br>
                <p class="is-size-5">
                  <span class="icon is-small">
                    <i class="far fa-calendar-alt"></i>
                  </span>
                  Date Played: <%= match.date_played %>
                </p>
                <%= render match %>
              </div>
              <footer class="card-footer">
                <a href="<%= match_path(match) %>" class="card-footer-item has-background-primary-light">See this match</a>
              </footer>
            </div>
          </div>
        <% end %>
  </div>
</section>

quiniela/app/views/matches/new.html.erb
<section class="section animate__animated animate__zoomIn animate__faster">
  <div class="container">
    <% if notice %>
      <div class="notification is-danger">
        <%= notice %>
      </div>
    <% end %>
    <div class="box">
      <div class="control has-text-left mt-4">
        <%= link_to all_matches_path, class: "button is-danger" do %>
          <span class="icon">
            <i class="fas fa-arrow-left"></i>
          </span>
          <span>Back</span>
        <% end %>
      </div>
      <h1 class="title">New match</h1>

      <%= form_with model: @match, class: "form" do |form| %>
        <div class="field">
          <%= form.label :date_played, class: "label" %>
          <div class="control">
            <%= form.date_field :date_played, class: "input" %>
          </div>
        </div>

        <div class="field">
          <%= form.label :team1_id, class: "label" %>
          <div class="control">
            <div class="select">
              <%= form.collection_select :team1_id, Team.all, :id, :name, { prompt: "Select Team 1" }, class: "select" %>
            </div>
          </div>
        </div>

        <div class="field">
          <%= form.label :team2_id, class: "label" %>
          <div class="control">
            <div class="select">
              <%= form.collection_select :team2_id, Team.all, :id, :name, { prompt: "Select Team 2" }, class: "select" %>
            </div>
          </div>
        </div>

        <div class="field"> 
          <%= form.label :goals_team_1, class: "label" %>
          <div class="control">
            <div class="select">
              <%= form.select :goals1, options_for_select([["Not Played Yet", ""], *(0..10)]), {}, class: "input" %>
            </div>
          </div>
        </div>

        <div class="field"> 
          <%= form.label :goals_team_2, class: "label" %>
          <div class="control">
            <div class="select">
              <%= form.select :goals2, options_for_select([["Not Played Yet", ""], *(0..10)]), {}, class: "input" %>
            </div>
          </div>
        </div> 

        <div class="field is-grouped">
          <div class="control">
            <%= form.submit "Submit", class: "button is-primary" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</section>

quiniela/app/views/matches/show.html.erb
<section class="section animate__animated animate__zoomIn animate__faster">
  <div class="container">
    <div class="box">
      <% if notice %>
        <div class="notification is-primary">
          <%= notice %>
        </div>
      <% elsif alert %>
        <div class="notification is-danger">
          <%= alert %>
        </div>
      <% end %>
      <%= render @match %>
      <div id="match">
        <div class="control has-text-left mt-4">
          <%= link_to all_matches_path, class: "button is-danger" do %>
            <span class="icon">
              <i class="fas fa-arrow-left"></i>
            </span>
            <span>Back</span>
          <% end %>
        </div>
        <h2 class="title">Match # <%= @match.id %></h2>
        <div class="card-content has-text-centered">
          <p class="is-size-4 has-text-weight-bold">
            <%= truncate(Team.find_by(id: @match.team1_id).name, length: 100) %> 
            vs 
            <%= truncate(Team.find_by(id: @match.team2_id).name, length: 100) %>
          </p> <br>
          <p class="is-size-5">
            <span class="icon is-small">
              <i class="fa fa-futbol"></i>
            </span> 
            <%= @match.goals1 %> - <%= @match.goals2 %>
          </p>  <br>
          <p class="is-size-5">
            <span class="icon is-small">
              <i class="far fa-calendar-alt"></i>
            </span>
            Date: <%= @match.date_played %>
          </p>
          <%= render @match %>
        </div>
        <footer class="card-footer">
          <% if @current_player.role_id == 2 %>
            <%= link_to "Edit Match", edit_match_path(@match), class: "card-footer-item has-background-primary" %>
          <% elsif @match.date_played > Time.current %>
            <%= link_to "Make a Prediction", new_prediction_path(match_id: @match.id), class: "card-footer-item has-background-primary" %>
          <% end %>
        </footer>
        <% if @current_player.role_id == 2 %>
          <%= button_to "Delete this Match", @match, method: :delete, data: { confirm: "Are you sure?" }, class: "button is-danger mt-5" %>
        <% end %>
      </div>
    </div>
  </div>
</section>