quiniela/config/routes.rb
Rails.application.routes.draw do
  scope '/home' do 
    resources :players do
      collection do
        get :sign_up
        get :login
        get :logout
        post :login
        get 'profile/:id' => 'players#show', as: :profile
      end
    end
    resources :predictions
    resources :matches do
      collection do 
        get :all
      end
    end
    resources :teams
    resources :roles
    resources :leaderboards
    get '/', to: 'players#home', as: :home
    get '/welcome', to: 'players#root', as: :root
  end 

  scope '/api' do
    resources :api_matches
    scope '/get_token' do
      get '/', to: 'application_api#get_token'
    end
    scope '/authorize_request' do
      get '/', to: 'application_api#authorize_request'
    end
  end
end

quiniela/app/models/player.rb
class Player < ApplicationRecord

    after_destroy :destroy_leaderboard, :destroy_predictions


    # validations
    validates :username, presence: true, uniqueness: true
    validates :password, presence: true

    # associations
    belongs_to :role
    has_many :predictions
    has_one :leaderboard

    # enums
    enum status: {
        active: "active",
        inactive: "inactive"
    }

    # callbacks
    after_create :set_role_id

    # methods
    def set_role_id
        self.update(role_id: 1)
    end

    def destroy_leaderboard
        self.leaderboard.destroy
    end

    def destroy_predictions
        self.predictions.destroy_all
    end
end

quiniela/app/controllers/players_controller.rb
class PlayersController < ApplicationController
  include PlayersHelper

  before_action :set_player, only: %i[ show edit update destroy ]
  
  # GET /players or /players.json
  def index
    @players = Player.all
  end
  
  # GET /players/1 or /players/1.json
  def show
    Leaderboard.update_leaderboard
  end
  
  # GET /players/new
  def new
    @player = Player.new
    session[:saved_location] = request.referer

  end
  
  # GET /players/1/edit
  def edit
  end
  
  # POST /players or /players.json
  def create
    @player = Player.new(player_params)
    @player.role_id = 1
    @player.build_leaderboard(points: 0)

    

    if @player.save
      PlayerMailer.with(player: @player).welcome_player_email.deliver_now
      redirect_to login_players_url(@player), notice: "Player was successfully created."
    else
      redirect_to sign_up_players_path , alert: "Username already exists."
    end
  end

  
  # PATCH/PUT /players/1 or /players/1.json
  def update
    respond_to do |format|
      if @player.update(player_params)
        format.html { redirect_to player_url(@player), notice: "Player was successfully updated." }
        format.json { render :show, status: :ok, location: @player }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end
  
  # DELETE /players/1 or /players/1.json
  def destroy
    @player.destroy
    session[:player_id ] = nil
    
    respond_to do |format|
      format.html { redirect_to home_path}
      format.json { head :no_content }
  
    end
  end
  
  
  # sign up method for players
  def sign_up 
    @player = Player.new
    respond_to do |format|
      format.html
      format.xml { render xml: @matches}
      format.json { render json: @matches}
    end
    # flash.discard(:notice)
  end
  
  # login method for players
  def login
    flash.discard(:notice)
    flash.discard(:alert)
    if request.post?
      # check if player exists
      @player = Player.find_by(username: params[:username])
      if @player && @player.password == params[:password]
        # set session variable
        session[:player_id] = @player.id
        # redirect to home/profile page with notice
        redirect_to home_path, notice: "Login successful."
      else
        # redirect back to login page with alert
        redirect_to login_players_path, alert: "Incorrect username or password."
      end
    end
    flash.discard(:notice)
  end
  

  # logout method for players
  def logout
    # reset session variable
    session[:player_id] = nil
    # redirect to login page
    redirect_to root_path
  end
  
  # home method for players
  def home 
    if session[:player_id]
      @player = Player.find(session[:player_id])
      @predictions = @player.predictions
    else
      redirect_to root_path
    end


  def root 
  end 


  end
  
  # show profile method for players
  def profile 
  end
  
  
  private
  
  # Use callbacks to share common setup or constraints between actions.
  def set_player
    @player = Player.find(params[:id])
  end

  # set current player
  def set_current_player
    if session[:player_id]
      @current_player = Player.find_by(id: session[:player_id])
    end
  end
  
  # Only allow a list of trusted parameters through.
  def player_params
    params.require(:player).permit(:id,
      :username,
      :password,
      :role_id
    )
  end
end

quiniela/app/helpers/players_helper.rb
module PlayersHelper
    def leaderboard_position(player)
      leaderboard = Leaderboard.order(points: :desc)
      position = leaderboard.index { |entry| entry.player_id == player.id }
      position ? position + 1 : 'N/A' # Retorna la posición o 'N/A' si el jugador no está en la leaderboard.
    end
  end
  

quiniela/app/views/players/_form.html.erb
<%= form_with(model: player) do |form| %>
  <% if player.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(player.errors.count, "error") %> prohibited this player from being saved:</h2>

      <ul>
        <% player.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

quiniela/app/views/players/_player.html.erb
<div id="<%= dom_id player %>">
</div>

quiniela/app/views/players/edit.html.erb
<section class="section">
  <div class="container">
    <div class="box has-content-centered">
      <div class="control has-text-left mt-4">
        <%= link_to player_path, class: "button is-danger" do %>
          <span class="icon">
            <i class="fas fa-arrow-left"></i>
          </span>
          <span>Back</span>
        <% end %>
      </div>
      <h1 class="title">Editing player</h1>
      <div class="is-flex is-flex-direction-column is-align-items-center">
        <%= form_with model: @player, local: true, html: { class: "form" } do |form| %>
          <div class="field">
            <%= form.label :username, class: "label" %>
            <div class="control">
              <%= form.text_field :username, class: "input", placeholder: "Username" %>
            </div>
          </div>

          <div class="field">
            <%= form.label :password, class: "label" %>
            <div class="control">
              <%= form.password_field :password, class: "input", placeholder: "Password" %>
            </div>
          </div>

          <div class="field">
            <div class="control">
              <%= form.submit "Update", class: "button is-primary" %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</section>

quiniela/app/views/players/home.html.erb
<style>
  /* Estilo personalizado para ajustar la card */
  .custom-card {
    height: 50vh; /* Puedes ajustar esta altura según tus necesidades */
    display: flex;
    flex-direction: column;
    justify-content: center;
    align-items: center;
  }

  /* Ajustar el tamaño del icono y agregar espaciado entre el icono y el texto */
  .custom-card .icon {
    font-size: 6rem;
    margin-bottom: 1rem;
  }

  /* Estilo para el texto del título */
  .custom-card .title {
    margin-top: 30%;
  }

  /* Alinear los títulos de las cards entre sí */
  .columns {
    align-items: center;
  }
</style>
<section class="section">
  <div class="container">
    <div class="box has-text-centered animate__animated animate__slideInUp animate__faster">
      <h1 class="title">Welcome <%= @player.username %></h1>
      <div class="columns is-centered">
        <div class="column is-one-third">
          <a href="<%= all_matches_path %>" class="card has-background-primary has-text-white custom-card">
            <div class="card-content">
              <span class="icon is-large">
                <i class="fas fa-futbol"></i>
              </span>
              <br>
              <br>
              <br>
              <p class="title">Matches</p>
            </div>
          </a>
        </div>

        <div class="column is-one-third">
          <a href="<%= leaderboards_path %>" class="card has-background-info has-text-white custom-card">
            <div class="card-content">
              <span class="icon is-large">
                <i class="fas fa-trophy"></i>
              </span>
              <br>
              <br>
              <p class="title">Leaderboard</p>
            </div>
          </a>
        </div>

        <% if @player.role_id == 2 %> 
          <div class="column is-one-third">
            <a href="<%= teams_path %>" class="card has-background-danger has-text-white custom-card">
              <div class="card-content">
                <span class="icon is-large">
                  <i class="fas fa-users"></i> <!-- Icono de equipos -->
                </span>
                <br>
                <br>
                <br>
                <p class="title">Teams</p> <!-- Título para configuración de equipos -->
              </div>
            </a>
          </div>
        <% else %>
          <div class="column is-one-third">
            <a href="<%= new_prediction_path %>" class="card has-background-dark has-text-white custom-card">
              <div class="card-content">
                <span class="icon is-large">
                  <i class="fas fa-edit"></i>
                </span>
                <p class="title">Make a Prediction</p>
              </div>
            </a>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</section>

quiniela/app/views/players/index.html.erb
<p style="color: green"><%= notice %></p>


<h1>Players</h1>

<div id="players">
  <% @players.each do |player| %>
    <%= "Player #" + player.id.to_s%> <br>
    <%= render player %>
    <p>
      <%= link_to "Show this player", player %>
    </p>
  <% end %>
</div>

<%= link_to "New player", new_player_path %>

quiniela/app/views/players/login.html.erb
<br><br><br>
<div class="is-flex is-flex-direction-column is-align-items-center">
  <div class="box animate__animated animate__slideInUp animate__faster">
    <% if notice %>
      <div class="notification is-primary">
        <%= notice %>
      </div>
    <% elsif alert %>
      <div class="notification is-danger">
        <%= alert %>
      </div>
    <% end %>
    <h1 class="title">Log In</h1>

    <%= form_with model: @player, url: login_players_path do |form| %>
      <div class="field">
        <%= form.label :username, class: "label" %>
        <div class="control">
          <%= form.text_field :username, class: "input", placeholder: "Username" %>
        </div>
      </div>

      <div class="field">
        <%= form.label :password, class: "label" %>
        <div class="control">
          <%= form.password_field :password, class: "input", placeholder: "Password" %>
        </div>
      </div>
      
      <div class="field">
        <div class="control">
          <%= form.submit "Log In", class: "button is-primary" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

quiniela/app/views/players/new.html.erb
<h1>New player</h1>


<%= form_with model: @player do |form| %>
  <div>
    <%= form.label :username %> <br>
    <%= form.text_field :username %> 
  </div>

  <div>
    <%= form.label :password %> <br>
    <%= form.password_field :password %>
  </div>
  
  <br>
    <%= form.submit %>
  </div>

  <% end %>

<div>
  <%= link_to "Back to players", players_path %>
</div>

quiniela/app/views/players/root.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Football Pools App</title>
  <style>
    .gif {
      max-width: 40%;
      height: auto;
    }

    .app-title {
      color: #17a33c;
    }
  </style>
</head>
<body>
  <section class="section">
    <div class="container">
      <div class="box has-text-centered has-background animate__animated animate__slideInUp animate__faster">
        <div class="card-content has-text-centered">
          <h1 class="title is-1">
            Quiniel<span class="app-title">App</span>
          </h1>
          <p class="subtitle is-4 mt-3">Football Pools like never before.</p>
          <p class="subtitle is-6 mt-2">Please login or register to start playing</p>
          <div class="buttons is-centered mt-5">
            <a href="/home/players/login" class="button is-primary">Login</a>
            <a href="/home/players/sign_up" class="button is-link">Register</a>
          </div>
        </div>
        <%= image_tag('gif/ball.gif', alt: 'icon', class: 'gif') %>
      </div>
    </div>
  </section>
</body>
</html>

quiniela/app/views/players/show.html.erb
<section class="section animate__animated animate__slideInUp animate__faster">
  <div class="container is-fluid">
    <div class="notification is-primary">
      <%= notice %>
    </div>
    
    <div class="columns is-multiline">
      <div class="column is-6">
        <div class="box play">
          <div class="card">
            <div class="card-content has-text-centered">
              <h1 class="title"><%= @player.username %> </h1>
              <p class="has-text">Player ID #<%= @player.id %></p> 
              <p class="has-text"> Joined on: <%= @player.created_at.strftime("%B %d, %Y") %></p>
            </div>
            <div class="card-content has-text-centered">
              <h1 class="title">Account Settings</h1>
              <div class="buttons is-centered">
                <%= link_to "Edit Account", edit_player_path(@player), class: "button is-info" %>
                <%= button_to "Delete Account", @player, method: :delete, data: { confirm: "Are you sure?" }, class: "button is-danger" %>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div class="column is-6">
        <div class="box">
          <div class="card">
            <div class="card-content has-text-centered">
              <h1 class="title">Leaderboard Position</h1> <br>
              <p class="subtitle">You are currently ranked <%= leaderboard_position(@player) %>th! with <%= @player.leaderboard.points.to_s %> points.</p>
            </div> 
            <div class="card-content has-text-centered">
              <h1 class="title">Play</h1>
              <div class="buttons is-centered">
                <%= link_to "My Predictions", predictions_path(player_id: @current_player.id), class: "button is-primary" %>
                <%= link_to "Matches", all_matches_path, class: "button is-primary" %>
                <%= link_to "Leaderboard", leaderboards_path, class: "button is-primary" %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

quiniela/app/views/players/sign_up.html.erb
<br><br><br>
<div class="is-flex is-flex-direction-column is-align-items-center">
  <div class="box animate__animated animate__slideInUp animate__faster">
    <h1 class="title">Sign up</h1>
    <% if notice %>
      <div class="notification is-primary">
        <%= notice %>
      </div>
    <% elsif alert %>
      <div class="notification is-danger">
        <%= alert %>
      </div>
    <% end %>

    <%= form_with model: @player do |form| %>
      <div class="field">
        <%= form.label :username, class: "label" %>
        <div class="control">
          <%= form.text_field :username, class: "input", placeholder: "Username" %>
        </div>
      </div>

      <div class="field">
        <%= form.label :password, class: "label" %>
        <div class="control">
          <%= form.password_field :password, class: "input", placeholder: "Password" %>
        </div>
      </div>
      
      <div class="field">
        <div class="control">
          <%= form.submit "Sign Up", class: "button is-primary" %>
        </div>
      </div>
    <% end %>
  </div>
</div>